sonar.projectKey=notes-app-sonar
sonar.projectName=notes-app-sonar
sonar.organization=dapherooo
sonar.sourceEncoding=UTF-8

# Sumber & test
sonar.sources=src,.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

# Coverage (dari Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Long-lived branches configuration
sonar.branch.autoconfig.enabled=true

# (opsional) Sesuaikan jika pakai monorepo:
# sonar.working.directory=.sonar
