sonar.projectKey=dapherooo
sonar.projectName=tugas-project-digital-skola-devops
sonar.organization=DAP
sonar.sourceEncoding=UTF-8

# Sumber & test
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

# Coverage (dari Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclude node_modules and coverage from scan
sonar.exclusions=node_modules/**,coverage/**,loadtest/**
sonar.test.exclusions=node_modules/**
